-- begin FRAMEWORK_BASE_BILL
alter table FRAMEWORK_BASE_BILL add constraint FK_FRAMEWORK_BASE_BILL_ON_BZJG foreign key (BZJG_ID) references SEC_GROUP(ID)^
create index IDX_FRAMEWORK_BASE_BILL_ON_BZJG on FRAMEWORK_BASE_BILL (BZJG_ID)^
-- end FRAMEWORK_BASE_BILL
